### DISCUSSION TITLE
Apollo lambda server causes error in aws function

### DISCUSSION THREAD

**Discussion by Rahmo** [apollographql/apollo-server#5012] [Q&A] [answered]
Hi All here is a more detailed about the issue 
my lambda seems to fail to access Apollo Server entry
```{
  "errorType": "Error",
  "errorMessage": "EACCES: permission denied, open '/var/task/apollo-server.js'",
  "trace": [
    "Error: EACCES: permission denied, open '/var/task/apollo-server.js'",
    "    at Object.openSync (fs.js:462:3)",
    "    at Object.readFileSync (fs.js:364:35)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1025:18)",
    "    at Module.load (internal/modules/cjs/loader.js:863:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
    "    at Module.require (internal/modules/cjs/loader.js:887:19)",
    "    at require (internal/modules/cjs/helpers.js:74:18)",
    "    at _tryRequire (/var/runtime/UserFunction.js:75:12)",
    "    at _loadUserApp (/var/runtime/UserFunction.js:95:12)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)"
  ]
}
```

```
//my serverless.yml looks like 
service: apollo-server-lambda
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
functions:
  graphql:
    handler: apollo-server.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
          integration: lambda-proxy
      - http:
          path: graphql
          method: get
          cors: true
          integration: lambda-proxy
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packagerOptions:
      scripts:
        - npx prisma generate

```

```
//Webpack.config.js
const nodeExternals = require('webpack-node-externals');
const serverlessWebpack = require('serverless-webpack');
const CopyWebpackPlugin = require("copy-webpack-plugin");

module.exports = {
	entry: serverlessWebpack.lib.entries,
	devtool: 'source-map',
	externals: [nodeExternals()],
	mode: serverlessWebpack.lib.webpack.isLocal ? 'development' : 'production',
	module: {
		rules: [
			{
				test: /\.js$/,
				use: ["source-map-loader"],
				include: __dirname,
				enforce: "pre"
			},
			{
				test: /\.tsx?$/,
				loader: 'ts-loader',
				options: {
					// disable type checker - we will use it in fork plugin
					transpileOnly: true
				},
				include: __dirname,
				exclude: /node_modules/
			},
			{
				test: /\.mjs$/,
				include: /node_modules/,
				type: "javascript/auto",
			}
		]
	},

	plugins: [
		new CopyWebpackPlugin(["./prisma/schema.prisma"]),
	],
	optimization: {
		minimize: false,
	},
	resolve: {
		extensions: ['.ts', '.js'],
	},
	target: 'node',
};
```

```
//apollo-server.ts
import { ApolloServer } from 'apollo-server-lambda';
import { PrismaClient } from "@prisma/client";
import { resolvers } from './src/resolvers';
import { typeDefs } from './src/type-defs';
import {FeedsAPI} from "./datasources/feeds";

const prisma = new PrismaClient()

process.env.DATABASE_URL = "a url"

const apolloServer = new ApolloServer({
    resolvers,
    typeDefs,
    dataSources: () => ({
        feedsAPI: new FeedsAPI({ prisma }),
    }),
    // context: ({ event, context }) => ({
    //     headers: event.headers,
    //     functionName: context.functionName,
    //     event,
    //     context,
    // })
});

export const graphqlHandler = apolloServer.createHandler({
    cors: {
        origin: true,
        credentials: true,
    },
});
```
