### ISSUE TITLE
Serverless - Syntax error in module 'graphql': SyntaxError

### ISSUE THREAD

**Issue by rodrigooler** [apollographql/apollo-server#1532]
I am currently creating a test project to test serverless with apollo-server, while running the command to run serverless-offline the project works standard, but when I perform serverless deploy I am not getting access to the playground ... I am getting the error below when running serverless log on function playground.

I am using version 2.

```yaml
service: test
app: test
tenant: test

plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs6.10
functions:
  graphql:
    handler: graphql.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
  playground:
    handler: graphql.graphqlHandler
    events:
    - http:
        path: playground
        method: get
        cors: true
```
![captura de tela 2018-08-15 as 02 29 03](https://user-images.githubusercontent.com/5496931/44132926-052f65c6-a033-11e8-8e20-bd1d449424f3.png)
