### ISSUE TITLE
lambda: playground Server cannot be reached

### ISSUE THREAD

**Issue by Kcin1993** [apollographql/apollo-server#2136]
Hi team,

### Intended outcome

Using `"apollo-server-lambda": "^2.3.1"` expect the playground work fine.

---

### Actual outcome

Outcome in Playground webiste right side show 
```
{
  "error": "Response not successful: Received status code 403"
}
```

Check the browser console. The network's response in playground is `{"message":"Forbidden"}`

Note. I can test my graphQL api with curl command or aws lambda test. Only playground can not work fine.

---

### How to reproduce the issue

Here is my serverless.yml
```yml
service: jk-bot

custom:
  BOT_FB: "jk-bot-fb-table"

provider:
  name: aws
  runtime: nodejs8.10
  stage: v1
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["JkBotFb", "Arn"] }
  environment:
    BOT_FB: ${self:custom.BOT_FB}

resources:
  Resources:
    JkBotFb:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.BOT_FB}

functions:
  graphql:
    handler: handler.graphql
    events:
      - http:
          path: graphql
          method: POST
          cors: true
      - http:
          path: graphql
          method: GET
          cors: true
```

Here is my handler.js
```javascript
const { ApolloServer, gql } = require("apollo-server-lambda");
const { botTypeDef, botResolvers } = require("./models/bot");

const typeDefs = gql`
  ${botTypeDef}
`;
const resolvers = botResolvers;

const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: ({ event, context }) => ({
    headers: event.headers,
    functionName: context.functionName,
    event,
    context
  }),
  playground: {
    settings: {
      "request.credentials": "same-origin"
    }
  }
});

exports.graphql = server.createHandler({
  cors: {
    origin: "*",
    credentials: true
  }
});
```

### Issue might relative
* https://github.com/apollographql/apollo-server/issues/1500
* https://github.com/prisma/graphql-playground/issues/748
* https://github.com/prisma/graphql-playground/issues/826

---

Could anyone help this situation. Any better idea?
