### ISSUE TITLE
405 Apollo supports only GET/POST requests.

### ISSUE THREAD

**Issue by btibarra** [apollographql/apollo-server#2362]
Hello,

i'm trying to use apollo-server-lambda to deploy my graphql api. This are my settings:

```
// graphql.js
const { ApolloServer } = require('apollo-server-lambda');
const { schema } = require('./app/schema');

const server = new ApolloServer({
  schema,
  context: ({ event, context }) => ({
    headers: event.headers,
    ...
  })
});

exports.graphqlHandler = server.createHandler({
  cors: {
    origin: '*',
    methods: ['POST', 'GET'],
    allowedHeaders: ['Content-Type', 'Origin', 'Accept']
  }
});
```

```
# serverless.yml
service: apollo-lambda
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs8.10
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
          integration: LAMBDA

```

When I do a post i get this message:
```{
  "body": "Apollo Server supports only GET/POST requests.",
  "statusCode": 405,
  "headers": {
    "Allow": "GET, POST",
    "Access-Control-Allow-Methods": "POST,GET,OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type,Origin,Accept",
    "Access-Control-Allow-Origin": "*"
  }
}
```
