### ISSUE TITLE
 Cannot read property 'Access-Control-Request-Headers' of undefined

### ISSUE THREAD

**Issue by incompletude** [apollographql/apollo-server#2509]
I have found this issue, related to mine, but I could not found a solution to my problem.

https://github.com/apollographql/apollo-server/issues/1560

`serverless.yml`:

```
service: graphql-aws

provider:
  name: aws
  runtime: nodejs8.10
functions:
  graphql:
    handler: graphql.graphqlHandler
    environment:
      SLS_DEBUG: true
    events:
      - http:
          path: graphql
          method: post
          cors: true
          integration: lambda-proxy
      - http:
          path: graphql
          method: get
          cors: true
          integration: lambda-proxy
```

`graphql.js`:

```
const { ApolloServer, gql } = require('apollo-server-lambda')

const typeDefs = gql`
  type Query {
    hello: String
  }
`

const resolvers = {
  Query: {
    hello: () => 'Hello world!',
  },
}

const server = new ApolloServer({ typeDefs, resolvers })

exports.graphqlHandler = server.createHandler({
  cors: {
    origin: '*',
    credentials: true,
  },
})
```

Test:

`serverless invoke local --function graphql --data '{ "httpMethod": "POST", "body": { "query": "{ hello }" }}'`

Error:

`Cannot read property 'Access-Control-Request-Headers' of undefined`

Can someone help me solving this?
