### ISSUE TITLE
Integration Lambda results in "Apollo Server supports only GET/POST requests."

### ISSUE THREAD

**Issue by savnik** [apollographql/apollo-server#3678]
Apollo version: apollo-server-lambda@2.9.16

When using serverless with parameter `integration: lambda` the http method is modified to be named `method` where as without that parameter the http method is named `httpMethod`.
This cause the code here: https://github.com/apollographql/apollo-server/blob/1f279c1ed6cebf2203aa430294f4062e4317822b/packages/apollo-server-core/src/runHttpQuery.ts#L210-L238
to throw the error.

A possible fix is to check both `httpMethod` and `method` in https://github.com/apollographql/apollo-server/blob/1f279c1ed6cebf2203aa430294f4062e4317822b/packages/apollo-server-core/src/runHttpQuery.ts#L210

A serverless.yml example is provided here:
``` 
functions:
  create:
    handler: posts.create
    events:
      - http:
          method: get
          path: whatever
          integration: lambda
```

Documentation on https://www.apollographql.com/docs/apollo-server/deployment/lambda/ could be updated with a note on this.

Other places that may also be looked at:

https://github.com/apollographql/apollo-server/blob/1f279c1ed6cebf2203aa430294f4062e4317822b/packages/apollo-server-lambda/src/lambdaApollo.ts#L36

https://github.com/apollographql/apollo-server/blob/1f279c1ed6cebf2203aa430294f4062e4317822b/packages/apollo-server-lambda/src/ApolloServer.ts#L152
