### ISSUE TITLE
Playground is not loading with apollo-server-lambda

### ISSUE THREAD

**Issue by lealexandre** [apollographql/apollo-server#4210]
### This is:
Bug

### Specifications
OS: Win10
Browser: Chrome

### Expected Behavior
Open the GraphQL API URL - and mongodb query to work

Actual Behavior
Refresh the GraphQL API URL and it shows {"message": "Internal server error"}
Don't refresh the  GraphQL API URL and the queries work

### Steps to Reproduce the Problem
I'm trying to connect a mongodb via mongoose. After deployment, the playground loads depending on the input URL . 

STEP 1. I deploy the following code

my index.js
```
const { ApolloServer, gql } = require('apollo-server-lambda');
const mongoose = require('mongoose');

let conn = null;
conn = mongoose.createConnection('mongodb://username:password@cluster0-xngqr.mongodb.net/mydb?retryWrites=true');
conn.model('User', new mongoose.Schema({ name: String }));

const M = conn.model('User');

const typeDefs = gql`
    type Query {
      hello: String
      getUsers: [User]
  }
  type User {
        id: ID!
        name: String
        email: String
  }
`;

const resolvers = {
  Query: {
    hello: () => {return `hey sup ? `; },
    getUsers: async () => await conn.model('User').find()
  }
}

const server = new ApolloServer({typeDefs,resolvers});

exports.graphqlHandler = server.createHandler({
  cors: {
    origin: true,
    credentials: true,
  },
});

```
My serverless.yml
```
service: graphql-lambda

provider:
  name: aws
  runtime: nodejs12.x

functions:
  graphql:

    handler: graphql.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true
```
sls deploy

STEP 2. Open the browser with the aws url
Result: the playground loads **correctly** but the query return:  "error": { "message": "Internal server error" }
![Screenshot_65](https://user-images.githubusercontent.com/10567114/83925060-6fe2bf80-a743-11ea-824b-dbb7eab2353d.jpg) 

STEP 3. Change the connect url to

`conn = mongoose.createConnection('mongodb+srv://username:password@cluster0-xngqr.mongodb.net/mydb?retryWrites=true');`

STEP 4. Deploy and I DON'T REFRESH the browser
Result: the queries works! 
![Screenshot_63](https://user-images.githubusercontent.com/10567114/83924941-15e1fa00-a743-11ea-9f44-933d0813006a.jpg)

**BUT** as soon as I refresh the browser, the playground is gone and I get the error: {"message": "Internal server error"}

![Screenshot_64](https://user-images.githubusercontent.com/10567114/83924952-1c707180-a743-11ea-9804-c17a9e04ec04.jpg)
