### ISSUE TITLE
Unable to compile project with yarn2/PnP installation

### ISSUE THREAD

**Issue by oliversalzburg** [apollographql/apollo-server#4451]
I have a TypeScript project using yarn2/PnP for dependencies. When I try to build my project, it fails with the following output:
```shell
.yarn/cache/apollo-engine-reporting-protobuf-npm-0.5.2-15aa08f143-f49534868b.zip/node_modules/apollo-engine-reporting-protobuf/dist/protobuf.d.ts:1:23 - error TS2307: Cannot find module 'long' or its corresponding type declarations.

1 import * as Long from "long";
                        ~~~~~~


Found 1 error.
```

This project is using apollo-server-koa@2.16.1 and contains no code other than `import { ApolloServer, gql } from "apollo-server-koa";`

To my understanding, this error is due to the fact that `apollo-engine-reporting-protobuf` neglects to declare any actual dependencies. It imports an external module and then simple re-exports all symbols. Those can not be found by the TypeScript compiler, because the dependency graph is not set up to allow them to be loaded, as they are not dependencies of `apollo-engine-reporting-protobuf`.

Modules need to declare all dependencies and not rely on hoisting to access them.

**Comment by xenoterracide** [comment]
same issue

**Comment by oliversalzburg** [comment]
I actually no longer have this issue and I don't remember how I fixed it :(

**Comment by xenoterracide** [comment]
you probably have `packageExtensions` in your yarnrc, I've had to add quite a few for `apollo-`

```yaml
packageExtensions:
  apollo-engine-reporting-protobuf@^0.5:
    dependencies:
      long: '^4'
      '@types/long': '^4'
      '@apollo/protobufjs': '^1'
  apollo-reporting-protobuf@^0.6:
    dependencies:
      long: '^4'
      '@types/long': '^4'
  apollo-server-testing@^2:
    dependencies:
      apollo-server-types: '^0.6'
  apollo-server-plugin-response-cache@^0.5:
    dependencies:
      apollo-server-types: '^0.6'
```

**Comment by oliversalzburg** [comment]
The only one relating to Apollo I have is:
```yml
packageExtensions:
  "@apollographql/apollo-tools@*":
    peerDependencies:
      graphql: "*"
```
