### ISSUE TITLE
Memory Leak Lambda

### ISSUE THREAD

**Issue by juanem1** [apollographql/apollo-server#4733]
Hi, I have noticed a memory leak with the library ***apollo-server-lambda*** running a basic example.
This is not happening if I use apollo-server. As you can see I ran 50 request and goes from 90MB to 376MB.
I'm using:
- apollo-server-lambda@2.19.0
- serverless-offline@6.8.0

OS: Ubuntu 20.04.1 LTS
Node: v12.19.0

The code is:
```javascript
const { ApolloServer, gql } = require('apollo-server-lambda')

const typeDefs = gql`
  type Query {
    hello: String
  }
`
const resolvers = {
  Query: {
    hello: () => 'Hello world!'
  }
}

const server = new ApolloServer({
  typeDefs,
  resolvers,
  playground: true,
  introspection: true
})

exports.graphqlHandler = server.createHandler()
```
The serverless.yml configuration is:
```yml
service: my-api

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: development

functions:
  graphql:
    handler: src/index.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
```

![memoryLeakBase](https://user-images.githubusercontent.com/793514/99123464-02369b80-25df-11eb-9ca3-f9cc22a606bb.png)
![MemoryLeakAfter10req](https://user-images.githubusercontent.com/793514/99123456-ffd44180-25de-11eb-953b-3b5c74f6e768.png)
![MemoryLeakAfter50Req](https://user-images.githubusercontent.com/793514/99123460-019e0500-25df-11eb-91ac-e33c1fe07d2b.png)
