### ISSUE TITLE
apollo-server-lambda 'Access-Control-Allow-Credentials' header in the response is '' (empty)

### ISSUE THREAD

**Issue by danieljarrett74** [apollographql/apollo-server#5447]
I'm trying to get my react/apollo graphql app working on AWS with no luck.
I'm serving my api via https://api.mydomain.com/v1/graphql and my app from https://app.mydomain.

I'm always getting back the following error:
> Access to fetch at 'https://api.mydomain.com/v1/graphql' from origin
> 'https://app.mydomain' has been blocked by CORS policy: Response to
> preflight request doesn't pass access control check: The value of the
> 'Access-Control-Allow-Credentials' header in the response is '' which
> must be 'true' when the request's credentials mode is 'include'.**

When accessing my add via chrome I can see the graphql server gets requested twice:

firstly there's an OPTIONS request, the headers look like this:
```
Request URL: https://api.mydomain.com/v1/graphql
Request Method: OPTIONS
Status Code: 200 
Remote Address: 65.8.134.31:443
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-headers: Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent
access-control-allow-methods: OPTIONS,GET,POST
access-control-allow-origin: https://app.mydomain.com
content-length: 1
content-type: application/json
date: Thu, 08 Jul 2021 10:32:32 GMT
via: 1.1 89g87gouygiuygo7g98giuygi.cloudfront.net (CloudFront)
x-amz-apigw-id: CJYaEHs0AErMF1UQ=
x-amz-cf-id: cBIL07Z7k5BFtG_eTG31QxYAiGk76fkuygjpjwn3NDMbt7M1Z7DOg==
x-amz-cf-pop: MEL50-C1
x-amzn-requestid: 87ab12be-394c-4f56-97b6-896giuyg8
x-cache: Miss from cloudfront
:authority: api.mydomain.com
:method: OPTIONS
:path: /v1/graphql
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,pl-PL;q=0.8,pl;q=0.7,es;q=0.6
access-control-request-headers: apollographql-client-name,apollographql-client-version,content-type
access-control-request-method: POST
cache-control: no-cache
origin: https://app.mydomain.com
pragma: no-cache
referer: https://app.mydomain.com/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-site
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
```

and secondly with the Query, the headers look like this, and this is the one which produces the CORS error:
```
Request URL: https://api.mydomain.com/v1/graphql
Referrer Policy: strict-origin-when-cross-origin
Provisional headers are shown
accept: */*
apollographql-client-name: react-web-client
apollographql-client-version: 1.3
content-type: application/json
Referer: https://app.mydomain.com/
sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

```

I'm using Apollo Client like so:
```
....
import {ApolloClient, ApolloProvider, HttpLink, InMemoryCache} from '@apollo/client';


const cache = new InMemoryCache();
const link = new HttpLink({
    uri: 'https://api.mydomain.com/v1/graphql',
    credentials: 'include',
    fetchOptions: {
        mode: "cors",
      },
});

const client = new ApolloClient({
    cache: cache,
    link: link,

    name: 'react-web-client',
    version: '1.3',
    queryDeduplication: false,
    defaultOptions: {
        watchQuery: {
            fetchPolicy: 'cache-and-network',
        },
    }
});

....

```

My Apollo Server Lambda looks like this:
```
import { ApolloServer } from 'apollo-server-lambda'
import typeDefs from './schema/schema.graphql';
import resolvers from "./resolvers";


const server = new ApolloServer({
    typeDefs,
    resolvers,

});

exports.handler = server.createHandler({
  cors: {
    origin: true,
    credentials: true
  }
});
```

I've even tried ApolloServer v3 with:
```
const server = new ApolloServer({
    typeDefs,
    resolvers

});

exports.handler = server.createHandler({expressGetMiddlewareOptions: {    cors: {
    origin: "*",
    credentials: true,
  }}});
```

Maybe it's AWS causing the problem?  Here's my cloudformation part for the API Gateway for the Apollo Lambda (I tried with and without "method.response.header.Access-Control-Allow-Credentials")

```
MyApi:
  Type: 'AWS::ApiGateway::RestApi'
  Properties:
    Name: My-api
    EndpointConfiguration:
      Types:
        - EDGE

MyApiResource:
  Type: 'AWS::ApiGateway::Resource'
  Properties:
    ParentId: !GetAtt MyApi.RootResourceId
    RestApiId: !Ref MyApi
    PathPart: 'graphql'

MyApiMethodOptions:
  Type: AWS::ApiGateway::Method
  Properties:
    AuthorizationType: NONE
    HttpMethod: OPTIONS
    MethodResponses:
    - StatusCode: '200'
      ResponseParameters:
        method.response.header.Access-Control-Allow-Headers: true 
        method.response.header.Access-Control-Allow-Methods: true
        method.response.header.Access-Control-Allow-Origin: true
        method.response.header.Access-Control-Allow-Credentials: true
      ResponseModels: {}
    RequestParameters: {}
    Integration:
      Type: MOCK
      RequestTemplates:
        application/json: "{statusCode:200}"
      ContentHandling: CONVERT_TO_TEXT
      IntegrationResponses:
      - StatusCode: '200'
        ResponseParameters:
          method.response.header.Access-Control-Allow-Origin: "'*'"
          method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
          method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET,POST'"
          method.response.header.Access-Control-Allow-Credentials: "'true'"
        ResponseTemplates:
          application/json: |-
            #set($origin = $input.params("Origin"))
            #if($origin == "") #set($origin = $input.params("origin")) #end
            #if($origin.matches(".+")) #set($context.responseOverride.header.Access-Control-Allow-Origin = $origin) #end
    ResourceId:
      Ref: MyApiResource
    RestApiId:
      Ref: MyApi

MyApiMethodPost:
  Type: AWS::ApiGateway::Method
  Properties:
    HttpMethod: POST
    RequestParameters: {}
    ResourceId:
      Ref: MyApiResource
    RestApiId:
      Ref: MyApi
    ApiKeyRequired: false
    AuthorizationType: NONE
    Integration:
      IntegrationHttpMethod: POST
      Type: AWS_PROXY
      Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyApiLambdaFunction.Arn}/invocations
    MethodResponses: []

MyApiMethodGet:
  Type: AWS::ApiGateway::Method
  Properties:
    HttpMethod: GET
    RequestParameters: {}
    ResourceId:
      Ref: MyApiResource
    RestApiId:
      Ref: MyApi
    ApiKeyRequired: false
    AuthorizationType: NONE
    Integration:
      IntegrationHttpMethod: POST
      Type: AWS_PROXY
      Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyApiLambdaFunction.Arn}/invocations
    MethodResponses: []

MyApiDeployment:
  Type: 'AWS::ApiGateway::Deployment'
  Properties:
    RestApiId: !Ref MyApi
    StageName: v1
  DependsOn:
    - MyApiResource
    - MyApiMethodGet
    - MyApiMethodPost
    - MyApiMethodOptions


```

**Comment by glasser** [comment]
Did you try origin: true with AS3 rather than origin: '*'? The web security
model requires the origin to be reflected in order for credentials to be
honored and '*' is not good enough.

**Comment by danieljarrett74** [comment]
I solved this finally.  The problem was that I was using a MOCK integration for my OPTIONS request.  So it wasn't hitting the Lambda at all.

I fixed with this:
```
MyApiMethodOptions:
  Type: AWS::ApiGateway::Method
  Properties:
    HttpMethod: OPTIONS
    RequestParameters: {}
    ResourceId:
      Ref: MyApiResource
    RestApiId:
      Ref: MyApi
    ApiKeyRequired: false
    AuthorizationType: NONE
    Integration:
      IntegrationHttpMethod: POST
      Type: AWS_PROXY
      Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyApiLambdaFunction.Arn}/invocations
    MethodResponses: []


```

Note also that updating cloudformation stack doesn't necessarily deploy your change. You may also need tp manually deploy the api after you update your stack. I realised this right at the end, so I'm not even sure if my original post was the problem given I probably wasn't deploying my changes.
