### ISSUE TITLE
apollo-server-lambda with prisma causing massive latency and probably stack overflows with serverless framework

### ISSUE THREAD

**Issue by dborstelmann** [apollographql/apollo-server#5865]
Barebones apollo-server and apollo-server-lambda work fine.  But when I add a prisma client to the context, apollo-server-lambda has massive latency/stack overflow.  This seems like a super normal flow (serverless + apollo + prisma) and I can't get one query to run without like 10s latency (in an empty database).  If I just run the server with apollo-server locally it works fine or if I use apollo-server-lambda without a database it also works fine.  I'm happy to provide more info but if there is anywhere to point me here I am sure stuck.  Thanks!

```
import { ApolloServer } from 'apollo-server-lambda';
import { createContext } from 'context';
import { schema } from 'core';

const server = new ApolloServer({
  context: createContext(), // creates prisma client
  schema,
});

export const serverlessHandler = server.createHandler();
```

serverless.yml
```
functions:
  graphql:
    handler: packages/${self:service}/dist/index.serverlessHandler
    events:
      - http:
          path: /api
          method: post
          cors: true
      - http:
          path: /api
          method: get
          cors: true
```

Edit: I am generating a subgraph schema for managed federation FYI.

`core.ts`
```
export const schema = buildSubgraphSchema([{ resolvers, typeDefs }]);
```
