### ISSUE TITLE
apollo-server-lambda

### ISSUE THREAD

**Issue by wowzaaa** [apollographql/apollo-server#779]
Hi

I am trying to do a hello world app with apollo-server-lambda and serverless but for some reason i am stuck for half a day on "Apollo Server supports only GET/POST requests."

my handlers look like this:
```
var server = require('apollo-server-lambda'),
  graphQLSchema = require('./schema');

exports.graphqlHandler = server.graphqlLambda({ schema: graphQLSchema });
exports.graphiqlHandler = server.graphiqlLambda({
  endpointURL: '/production/graphql',
});
```

my schema looks like this:
```
const { makeExecutableSchema } = require('graphql-tools');

const typeDefs = `
    type User {
        id: Int!
        firstName: String!
        lastName: String!
    }
    type Query {
        users: [User]
    }`;

const resolvers = {
    Query: {
        users: () => [
            { id: 1, firstName: 'Tom', lastName: 'Coleman' },
            { id: 2, firstName: 'Sashko', lastName: 'Stubailo' },
            { id: 3, firstName: 'Mikhail', lastName: 'Novikov' },
        ]
    }
};

exports.schema = makeExecutableSchema({
    typeDefs,
    resolvers,
});
```

and my serverless.yml looks like this:
```
service: graphql-server
provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  stage: production
functions:
  graphql-server:
    handler: handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: get
          cors: true
      - http:
          path: graphql
          method: post
          cors: true
  graphiql-server:
    handler: handler.graphiqlHandler
    events:
      - http:
          path: graphiql
          method: get
          cors: true
```

so even though my graphiql endpoint works ... apollo server keeps telling me it can only answer to get / post

any idea why?

thanks
